### ISSUE TITLE
Use a proper logger

### ISSUE THREAD

**Issue by oierlauzi** [gigabit-clowns/xmipp4-core#102]
Use a proper logger instead of relying on `std::cout`/`std::cerr`. Decide which one to use. Currently we only have such calls in a couple of places, so this is a good time to take this decision.

- https://github.com/gabime/spdlog
- https://github.com/abumq/easyloggingpp
- https://github.com/emilk/loguru
- https://github.com/google/glog

I have good references of the first one, but IDK

**Comment by MartinSalinas98** [comment]
The first one looks like the most popular one by far, and is the only one that has passing badges on all the OSs we support here. I've never used any of them, but I'm a biy more inclined twards using spdlog
